language: php

php:
    - 7.0
    - 7.1
    - 7.2

branches:
    only:
        - master

before_script:
    - composer install

script:
    - bin/phpcs Api DependencyInjection --standard=PSR2 --extensions=php
    - phpunit
